### ISSUE TITLE
Reindexing may cause PostgreSQL database deadlocks

### ISSUE THREAD

**Issue by aperezdc** [aperezdc/synpurge#10]
They may show up on occasion, it seems that reindexing is the time when they like to appear. Most likely waiting some seconds and retrying the query would do (up to a maximum amount of times, and maybe passing to the next purge if `--keep-going` is used). Output looks as follows:

```
Traceback (most recent call last):
  File "/root/synpurge-env/bin/synpurge", line 9, in <module>
    load_entry_point('synpurge==3', 'console_scripts', 'synpurge')()
  File "/root/synpurge-env/lib/python3.4/site-packages/argh/dispatching.py", line 370, in __call__
    return self._dispatch()
  File "/root/synpurge-env/lib/python3.4/site-packages/argh/dispatching.py", line 382, in _dispatch
    dispatch(parser)
  File "/root/synpurge-env/lib/python3.4/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/root/synpurge-env/lib/python3.4/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/root/synpurge-env/lib/python3.4/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/root/synpurge/synpurge/cli.py", line 161, in purge
    pgdb.reindex()
  File "/root/synpurge/synpurge/pg.py", line 84, in reindex
    self._db.execute("REINDEX TABLE {}".format(table_name))
  File "/root/synpurge-env/lib/python3.4/site-packages/postgresql/driver/pq3.py", line 2311, in execute
    self._pq_complete()
  File "/root/synpurge-env/lib/python3.4/site-packages/postgresql/driver/pq3.py", line 2609, in _pq_complete
    self.typio.raise_error(x.error_message, cause = getattr(x, 'exception', None))
  File "/root/synpurge-env/lib/python3.4/site-packages/postgresql/driver/pq3.py", line 541, in raise_error
    self.raise_server_error(error_message, **kw)
  File "/root/synpurge-env/lib/python3.4/site-packages/postgresql/driver/pq3.py", line 532, in raise_server_error
    raise server_error
postgresql.exceptions.DeadlockError: deadlock detected
  CODE: 40P01
  LOCATION: File 'deadlock.c', line 956, in DeadLockReport from SERVER
  DETAIL: Process 13348 waits for AccessExclusiveLock on relation 16618 of database 16387; blocked by process 11716.
Process 11716 waits for RowExclusiveLock on relation 16611 of database 16387; blocked by process 13348.
  HINT: See server log for query details.
CONNECTION: [idle]
  client_address: ::1/128
  client_port: 56524
  version:
    PostgreSQL 9.4.9 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit
CONNECTOR: [Host] pq://synapse:***@localhost:5432
  category:
    CATEGORY:
      aliases: {}
    SET: 1
      --
      LIBRARY: /root/synpurge/synpurge/pglib/libsynapse.sql
DRIVER: postgresql.driver.pq3.Driver
```

**Comment by aperezdc** [comment]
Confirmed: this happens while reindexing is underway because `REINDEX` locks out tables for writing while it runs. We may want to do one or more of:

* Not triggering `REINDEX`.
* Triggering `REINDEX` only if fragmentation goes over a certain threshold.
* Using `DROP INDEX` followed by `CREATE INDEX` with the same parameters to re-create a completely new index.
* Figuring out whether it is possible to `CREATE INDEX` with a new name (and same parameters), then `DROP INDEX`, and then `ALTER` it to make the new index have the expected name.

**Comment by aperezdc** [comment]
One last alternative would be using `CREATE INDEX CONCURRENTLY` ([documentation](https://www.postgresql.org/docs/9.4/static/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY)), which does not lock tables but performs more I/O and needs additional code to handle cases in which index creation may fail.

**Comment by psaavedra** [comment]
I've ran manually this snippet of SQL code to perform a non blocking reindexation of the `state_groups_state` table on a synapse server. The idea behind this instructions is build a secondary index in backgroud and swap it when it is ready:

``` sql

-- Get the index related index for table
select pg_get_indexdef(idx.oid)||';'
from pg_index ind
  join pg_class idx on idx.oid = ind.indexrelid
  join pg_class tbl on tbl.oid = ind.indrelid
  left join pg_namespace ns on ns.oid = tbl.relnamespace
where tbl.relname = 'state_groups_state';

-- Create a new temporary index for the table: ^ spent more time; ^ more CPU usage; ^ somes times produce a invalid index but doesn't lock the table so ''synapse'' service is still intectable
CREATE INDEX CONCURRENTLY state_groups_state_type_idx_tmp ON state_groups_state USING btree (state_group, type, state_key);

-- If the new index is INVALID
DROP INDEX state_groups_state_type_idx_tmp;

-- If the new index is valid 
BEGIN;
ALTER TABLE state_groups_state CLUSTER ON state_groups_state_type_idx_tmp;
DROP INDEX state_groups_state_type_idx;
ALTER INDEX state_groups_state_type_idx_tmp RENAME TO state_groups_state_type_idx;
COMMIT;
```

Result:

- Space used before run the snippet: 40G
- Space used after run the snippet: 31G


If you are agree with the idea, I will be happy to submit a PR with the corresponding changes in the code for your tool.

**Comment by psaavedra** [comment]
As an additional extrapoint, the secondary index creation and the swap with the older one is from far faster than a `REINDEX` of the index. That is something that is indeed contradictory _a priori_  but justified because build a index from the scratch is simpler than a complex rebalancinx of a btree.

**Comment by psaavedra** [comment]
the **negative** part of this approaching is that it requires free disk space enough for a temporary redundant index.

**Comment by psaavedra** [comment]
lately, I've realized about, synapse uses `cluster`index (https://www.postgresql.org/docs/9.3/static/sql-cluster.html). To manage this, I'd suggest tothis changes in the first  SQL statement:


``` sql
-- Get the index related index for table
select idx.relname as index, pg_get_indexdef(idx.oid)||';' as definition, ind.indisclustered as clustered 
from pg_index ind
  join pg_class idx on idx.oid = ind.indexrelid
  join pg_class tbl on tbl.oid = ind.indrelid
  left join pg_namespace ns on ns.oid = tbl.relnamespace
where tbl.relname = 'state_groups_state'
and ind.indisvalid
and ind.indisready
;
```

**Comment by aperezdc** [comment]
@psaavedra: I have asked for a couple of small changes in the PR, but it is looking good and it would be great to have it merged. Thanks for helping out with this!

**Comment by aperezdc** [comment]
Thanks to @psaavedra we have now the code for the concurrent reindexing in `master`. I have added a `--concurrent` flag to the `purge` subcommand as well. Before closing this, I would like to stress-test the code a bit. Once we are confident in the concurrent reindexing code, I would like to:

- Rename the `reindex_full` config file option to `reindex_mode`, which would accept three possible values:
  - `"partial"` (same as `reindex_full=false`)
  - `"full"` (same as `reindex_full=true`)
  - `"concurrent"`

- Remove the `--concurrent` flag.

Once that is done, we can consider this issue closed, and then I would cut a new release.

**Comment by aperezdc** [comment]
@psaavedra: Have you been using the concurrent reindexing? If yes, could you comment whether you have found any issue using it? From my side there's no complaints, and it has been working just fine, though honestly I didn't use it much (maybe just a couple of times).

**Comment by muppeth** [comment]
Doesn't pg_repack do the job without locking tables?

**Comment by aperezdc** [comment]
@muppeth: It does, but we preferred to use only PostgreSQL built-in functionality, and use a method that is documented. While `pg_repack` looks neat, it adds compiled code which runs inside the PostgreSQL process, and we would rather avoid that.

**Comment by psaavedra** [comment]
@aperezdc  I can confirm it is working fine as expect. It was executed several times and no issues detected.

**Comment by aperezdc** [comment]
@psaavedra Thanks, let's then close this issue.
